CREATE TABLE [dbo].[ChatRoom]
(
	[Id] INT NOT NULL IDENTITY (1, 1),
	[Name] NVARCHAR(100) NOT NULL,
	[Created] DATETIMEOFFSET NOT NULL,

	CONSTRAINT [PK_ChatRoom] PRIMARY KEY CLUSTERED
	(
		[Id]
	),

	CONSTRAINT [UK_ChatRoom_Name] UNIQUE NONCLUSTERED
	(
		[Name]
	)
)
GO