CREATE TABLE [dbo].[ChatUser]
(
	[Id] INT NOT NULL IDENTITY (1, 1),
	[Name] NVARCHAR(100) NOT NULL,
	[Created] DATETIMEOFFSET NOT NULL, 

    CONSTRAINT [PK_ChatUser] PRIMARY KEY CLUSTERED
	(
		[Id]
	),

	CONSTRAINT [UK_ChatUser_Name] UNIQUE NONCLUSTERED
	(
		[Name]
	)
)
GO